export const EMAIL_IS_EMPTY = 'EMAIL_IS_EMPTY';
export const PASSWORD_IS_EMPTY = 'PASSWORD_IS_EMPTY';
export const PASSORT_DO_NOT_MATCH = 'PASSORT_DO_NOT_MATCH';
export const PASSWORD_LENGTH_MUST_BE_MORE_THAN_8 =
  'PASSWORD_LENGTH_MUST_BE_MORE_THAN_8';
export const WRONG_PASSWORD = 'WRONG_PASSWORD';
export const SOME_THING_WENT_WRONG = 'SOME_THING_WENT_WRONG';
export const USER_EXISTS_ALREADY = 'USER_EXISTS_ALREADY';
export const USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST';
export const TOKEN_IS_EMPTY = 'TOKEN_IS_EMPTY';
export const EMAIL_IS_IN_WRONG_FORMAT = 'EMAIL_IS_IN_WRONG_FORMAT';
export const VERIFICATION_CODE_EMPTY = 'VERIFICATION_CODE_EMPTY';
export const INVALID_VERIFICATION_CODE = 'INVALID_VERIFICATION_CODE';
export const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';
export const PHONE_NUMBER_IS_EMPTY = 'PHONE_NUMBER_IS_EMPTY';
export const FULL_NAME_IS_EMPTY = 'FULL_NAME_IS_EMPTY';
